### ISSUE TITLE
Confirm kubernetes workload strategy

### ISSUE THREAD

**Issue by jt-nti** [hyperledgendary/fabric-builder-k8s#15]
Need to check whether the builder is running the chaincode the best way.

The prototype creates a deployment since the Kubernetes documentation states...

> Usually you don't need to create Pods directly, even singleton Pods. Instead, create them using workload resources such as Deployment

This would almost certainly be the correct approach if the builder was able to start the chaincode as an external service, however the current Fabric builder implementation means that is not possible (see below).

Since the peer is still managing the chaincode workload in the traditional chaincode as a client case, a Pod may be the right option instead of a Deployment.

Note: the builder run executable should not exit while the chaincode is still running. The current prototype code just has a hack to stop the run executable exiting at all but it should be checking whether the chaincode is running and exiting if it has stopped.

It would be nice to fix the Fabric builder implementation to allow the k8s builder to run the chaincode as an external service. This is currently problematic because the builder is expected to provide the chaincode ID and TLS certificates in the release executable, which are actually provided to the builder's run executable... except this is not called for chaincode as an external service. The builder might be able to get the TLS certificates from the filesystem if it knew where to look, e.g. using a propagated environment variable, however the chaincode ID is not available. A possible fix might be to modify the Fabric builder implementation so that the run binary is optionally called even for chaincode as an external service.

**Comment by jkneubuh** [comment]
I was just looking at the pod stake under a microscope, and it's not working correctly with the use of pods.

From the Kube side the updates that need to be applied are: 

- Do not create `Pod` resources directly -- use `Deployments`

- IF we switch the parity and deploy CC "as a service" (peer --> CC gRPC handshake) then the builder will need construct a `Service` which exposes the Deployment/Pod/Port for the CC gRPCs receiver.

- Kube resources must set [owner references](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents) such that they are subject to a cascading delete when the peer is removed.


Effectively this behaves as `start`, not `run` in the builder lifecycle.  Which is consistent with how the peer lifecycle actually functions.

*IF* the peer CC lifecycle is altered such that it will support a reliable `run-with-restart` behavior, then we can switch from Deployment back to a Pod.  Until then we will need to rely on the reliability features provided by the Kube deployments.  (In the wild, pods can vanish for A LOT of reasons, most of which are not the actual process crashing.)

**Comment by jkneubuh** [comment]
Just to be clear - setting up a process to manage the pod lifecycle independently is not an idiomatic Kubernetes / best practice.

This is not the "kube way."  Use Deployments, and let Kube manage the watch / reconciliation loop.

**Comment by jt-nti** [comment]
It would be really _really_ nice to start the chaincode in server mode and let kubernetes take care of everything the "kube way", unfortunately Fabric currently gets in the way of that. If that ever changes...

**Comment by jkneubuh** [comment]
OK thanks @jt-nti I understand now the implications.  This is not ideal but unless we change the peer CC lifecycle to support "start" as a semantic, we will need to emulate the assumption of "fork + exec" from the builder to the CC process.  It is not the _Kube Way_ but it is the _Fabric Way_.   The correct verb in this context is *exec*. 

- If the `run` builder routine exits, the peer assumes the chaincode process has terminated.

- If the peer thinks chaincode is not running, it will attempt another sync `run` (exec)

- The peer will delay sending CC invocations to a chaincode process until AFTER it receives the "phone home" handshake.   (I just watched this occur and was pleasantly surprised to see the peer CLI / node blocking on a request to invoke the smart contract in the brief but non-zero interval of time between chaincode commit and the process / pod / CC coming online in k8s.) 

- The peer is "grumpy" and confused if multiple CC processes attempt to "phone home" on the same instance.


I think this is some of the necessary "battle hardening" required to weather the storms of running out on the open seas.  It is what it is ..... pods + sync wait / watch handlers in the builder `run` (exec) routine.

**Comment by jkneubuh** [comment]
Having the peer set up a sync watch on the pods is going to be ... brittle.   Can we consider a compromise between the _Kube Way_ and the _Fabric Way_?

- `run` will create replicasets.   Kube will manage / maintain the lifecycle of pods for the CC replicasets.

- `run` will check for an existing replicaset and/or use `apply` to modify an existing resource if present.  (This will help with the case when the peer decides to re-run the CC and it was created from a previous invocation.)

- `run` will enter a blocking wait(), waiting for the replicaset to reach a "ready" status.

- `run` will enter a blocking wait(), waiting forever and/or until the replicaset enters a "not ready" state.

- The CC replicaset will include a Kube owner reference.  If/when the peer is removed, this will scrub the CC instances from the cluster using the Kube GC. 


The compromise here is to pin the CC process lifecycle - not to a Pod, but to a "ready" replicaset (or deployment) in the cluster.  This should be _infinitely easier_ and more stable in the implementation of the async / blocking watch.  It is also more "kube friendly" and will tie in naturally to the existing builder lifecycle events.

**Comment by jt-nti** [comment]
@jkneubuh that looks like what you'd want to do if the builder/launcher framework gave you everything required at the `release` step instead of doing anything in `run`, i.e. just let kubernetes look after the chaincode using a replicaset (seems like a better match than deployment because the Fabric lifecycle is responsible for updates).

Whether it can work with the current Fabric versions depends on what the peer makes of uninvited chaincode connections which you'll get with the chaincode pods getting restarted by kubernetes- I'll give it a try though.

**Comment by jkneubuh** [comment]
So if / when the pod in a replicaset is terminated, the watch in the `run` method could release.  In addition to letting Kube manage the pods, the `run` routine needs to receive the async "replicaset went to 0 - not ready" event and exit.   Maybe this is too weird/buggy, as it opens the possibility that the new (restarted) CC pod will phone home to the peer when the peer thinks the CC is not running.    argh... maybe we really do need to watch pods with the legacy CC / builder lifecycle.

So many of these issues are minimized with the advent of CCaaS and the reversed handshake parity.   Maybe we can bend the lifecycle to our will?

**Comment by jt-nti** [comment]
Despite not taking full advantage of kubernetes, managing chaincode pods directly does seem like the closest fit to the current Fabric builder/launcher framework implementation. I definitely think it's worth using this builder as a way to probe that implementation, and potentially improve it, although that's probably only worthwhile if there's enough interest.
