### ISSUE TITLE
Use digests instead of image labels in chaincode package

### ISSUE THREAD

**Issue by jt-nti** [hyperledgendary/fabric-builder-k8s#22]
Docker tags are mutable which can cause problems if the tag is changed accidentally or maliciously.

To get the digest...

```shell
docker inspect ghcr.io/OWNER/IMAGE_NAME
```

Using both the tag (which would be ignored) _and_ digest in the current `image.json` would probably work already, e.g.

```json
{
  "name": "ghcr.io/OWNER/IMAGE_NAME",
  "tag": "TAG@sha256:82jf9a84u29hiasldj289498uhois8498hjs29hkuhs"
}
```

Enforce digests in the future by updating the `image.json` file to include `digest` instead of `tag`, e.g.

```json
{
  "name": "ghcr.io/OWNER/IMAGE_NAME",
  "digest": "82jf9a84u29hiasldj289498uhois8498hjs29hkuhs"
}
```

**Comment by jkneubuh** [comment]
The challenge with requiring image digests is that they are maintained ONLY for images that have been published to a container registry.  This makes it impossible / impractical to launch chaincode container images that have been built locally, loaded through the KIND control plane, or out of band from a registry.  IMO this is a showstopper, as it prevents the use of a local docker / containerd cache to run chaincode in a dev k8s.

Please can we relax the enforcement clause of this feature, allowing the [kube-conventions](https://kubernetes.io/docs/concepts/containers/images/#image-names) for specifying the container image using **either** the label or via digest hash.

Proposed update: 
```
{
  "image": "<container-registry>/<image-name>[ : <image-label> | @ <image-digest> ]? 
  [ "imagePullPolicy": { "IfNotPresent" | "Always" | "Never" } ]?
  [ "imagePullSecrets": <array of k8s secret references> ]? 
}
```

This compromise allows a CI/CD/distribution path to enforce a package with the 1:1 :: layer:chaincode pinning **AND** allows for a natural workflow in environments without access to a container registry.

**Comment by jt-nti** [comment]
Closing- latest versions use digests. See #29 for possible enhancement if this impacts usability in a dev environment too much.
